--- nmap-2.53/Makefile.in.tim	Thu Jun  8 17:41:49 2000
+++ nmap-2.53/Makefile.in	Thu Jun  8 17:43:24 2000
@@ -7,7 +7,8 @@
 sbindir = @sbindir@
 mandir = @mandir@
 srcdir = @srcdir@
-nmapdatadir = @datadir@/nmap
+datadir = @datadir@
+nmapdatadir = $(datadir)/nmap
 deskdir = $(prefix)/share/gnome/apps/Utilities
 
 CC = @CC@
